Textaland/Models/TranslationRequest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Textaland.Models
{
	public class TranslationRequest {
		public int Id { get; set; }
		public string _userId { get; set; }
		public int _numUpvotes { get; set; }
        [Required(ErrorMessage = "Name required")]
        public string _name { get; set; }
        [Required(ErrorMessage = "Please select language")]
		public string _language { get; set; }

		public TranslationRequest() {
			_numUpvotes = 0;
		}

		public void IncreaseNumUpvotes(){
			_numUpvotes++;
		}
	}
}

Textaland/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Textaland.Models;
using Textaland.DataAccessLayer;
using Textaland.Interface;

namespace Textaland.Controllers
{
    public class SearchController : Controller {

        private readonly ISubtitleFileRepo _sfr;
        private readonly ITranslationRequestRepo _trr;

        public SearchController() {
            _sfr = SubtitleFileRepo.Instance; 
            _trr = TranslationRequestRepo.Instance;
        }

        public SearchController(ISubtitleFileRepo sfr, ITranslationRequestRepo trr) {
            _sfr = sfr;
            _trr = trr;
        }
		
		// Post
		[HttpPost]
		public ActionResult SearchResult(FormCollection formdata) {

			//splits the string from the user into many strings, one string is one word.
			string sentence = formdata["leit"].ToLower();
			string[] words = sentence.Split(new char[] { ' ' });
			
			//Just get the subtitles that contains every string in "words"
			var searchResult = (from s in _sfr.GetAllSubtitles() select s);
			foreach (var w in words) {
				searchResult = (from s in searchResult
								where s._name.ToLower().Contains(w) 
								where s._readyForDownload == true
								select s );
			}

			return View(searchResult);
		}

		[HttpPost]
		public ActionResult SearchResultForRequests(FormCollection formdata) {

			//splits the string from the user into many strings, one string is one word.
			string sentence = formdata["leit2"].ToLower();
			string[] words = sentence.Split(new char[] { ' ' });

			//Just get the subtitles that contains every string in "words"
			var searchResult = (from t in _trr.GetAllTranslationRequests() select t);
			foreach (var w in words) {
				searchResult = (from t in searchResult where t._name.ToLower().Contains(w) select t);
			}
			return View(searchResult);
		}
	}
}

Textaland/Controllers/TranslationRequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Textaland.Models;
using Textaland.DataAccessLayer;
using Textaland.Interface;
using Microsoft.AspNet.Identity;

namespace Textaland.Controllers
{
	public class TranslationRequestController : Controller {

        private readonly ITranslationRequestRepo _requestRepo;
        private readonly ITranslationRequestUpvoteRepo _requestUpvoteRepo;

        TranslationRequest request = new TranslationRequest();

        TranslationRequestUpvote requestUpvote = new TranslationRequestUpvote();

        public TranslationRequestController(ITranslationRequestRepo requestRepo, 
            ITranslationRequestUpvoteRepo requestUpvoteRepo) {
                _requestRepo = requestRepo;
                _requestUpvoteRepo = requestUpvoteRepo;
                request._userId = "TestId";
        }

        public TranslationRequestController() {
            _requestRepo = TranslationRequestRepo.Instance;
            _requestUpvoteRepo = TranslationRequestUpvoteRepo.Instance;
        }

		

		//Get
        [Authorize]
		public ActionResult NewTranslationRequest() {

            List<SelectListItem> languages = new List<SelectListItem>();
            languages.Add(new SelectListItem { Text = "select" });
            languages.Add(new SelectListItem { Text = "ENG", Value = "ENG" });
            languages.Add(new SelectListItem { Text = "ISL", Value = "ISL" });

            ViewBag.ListOfLanguages = languages;

			return View();
		}

		[HttpPost]
        [Authorize]
		public ActionResult NewTranslationRequest(FormCollection formData) {
			String strName = formData["_name"];
			String strLanguage = formData["_language"];

			request._name = strName;
			request._language = strLanguage;
            if (request._userId != "TestId") {
                request._userId = User.Identity.GetUserId();
            }

			_requestRepo.AddTranslationRequest(request);
            return RedirectToAction("TranslationRequests", new { num = 0 });		
		}

		//Get
		public ActionResult TranslationRequests(int num) {


			//We give errors for the following actions..

			if (TempData["addVoteAgain"] != null) {
				ViewBag.votedAgain = TempData["addVoteAgain"].ToString();
			}
			else if (TempData["loggedIn"] != null) {
				ViewBag.requiredLogIn = TempData["loggedIn"].ToString();		
			}

			//The following success message is given if the user upvotes
			if (TempData["upVoteSuccess"] != null) {
				ViewBag.voteSuccess = TempData["upVoteSuccess"].ToString();
			}

            ViewBag.Upvotes = _requestUpvoteRepo.GetAllUpvotes();

            var requests = (from r in _requestRepo.GetAllTranslationRequests()
							orderby r._numUpvotes descending
							select r).Skip(num * 10).Take(10);
			var countRequests = from r in _requestRepo.GetAllTranslationRequests()
							orderby r._numUpvotes
							select r;

			TempData["requestPageNumber"] = num;
			ViewBag.allRequests = requests;
			ViewBag.countRequest = countRequests;

			return View();
		}

		//This operation Adds a Vote to a the "tr" requests.
		[HttpPost]
		public ActionResult AddVote(TranslationRequest request) {

			//Gets the user ID.
            var userId = User.Identity.GetUserId();

			//Checks if the user is registered and logged in.
			if (User.Identity.IsAuthenticated) {

				// Takes all the votes that have the same user and request ID.
				var upvotes = from u in _requestUpvoteRepo.GetAllUpvotes()
							  where u._userId == userId &&
							  u._requestId == request.Id
							  select u;
				if (upvotes.Count() == 0) {
					requestUpvote._requestId = request.Id;
					requestUpvote._userId = userId;
					_requestRepo.upVote(requestUpvote._requestId);
					_requestUpvoteRepo.AddUpvote(requestUpvote);
					TempData["upVoteSuccess"] = "Þú bættir við atkvæði á beiðni fyrir " + request._name;
				}
				else {
					TempData["addVoteAgain"] = "Aðeins er hægt að kjósa hverja beiðni einu sinni";
				}
			}
			else {
				TempData["loggedIn"] = "Aðeins innskráðir notendur geta framkvæmt þessa aðgerð";
				return RedirectToAction("TranslationRequests", new { num = 0 });
			}
	
            return RedirectToAction("TranslationRequests", new { num = 0 });
			
		}

		public ActionResult AnswerRequest(int id) {
			if (User.Identity.IsAuthenticated) {
				_requestRepo.RemoveTranslationRequestById(id);
			}
			else {
				TempData["loggedIn"] = "Aðeins innskráðir notendur geta framkvæmt þessa aðgerð";
				return RedirectToAction("TranslationRequests", new { num = 0 });
			}

			return RedirectToAction("UploadFile", "SubtitleFile", new { area = "" });		

		}
	}


	
}

Textaland/Views/TranslationRequest/NewTranslationRequest.cshtml
@model Textaland.Models.TranslationRequest

@{
    ViewBag.Title = "NewTranslationRequest";
}

<h2>Ný beiðni</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model._name, "Nafn", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model._name)
                @Html.ValidationMessageFor(model => model._name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model._language, "Tungumál skráar", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model._language, new SelectList(ViewBag.ListOfLanguages, "Value", "Text", "Selected"))
                @Html.ValidationMessageFor(model => model._language)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Senda" class="btn btn-info" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Textaland/Views/TranslationRequest/TranslationRequests.cshtml
<div class="jumbotron" style="background: none">
    <center>
        <h1>ÓSVARAÐAR BEIÐNIR</h1>
        <hr />
    </center>
</div>

<div class="form-group" style="margin-bottom: 30px">
    <label class="control-label" for="searchInput"></label>
    <center>
        @using (Html.BeginForm("SearchResultForRequests", "Search", FormMethod.Post)) 
        {
            <input type="text" name="leit2" id="leit2" value="Leitaðu að beiðni hér" 
                   style="text-align: center" onfocus="value=''" />
            <button class="btn btn-info btn-sm" title="Leita" type="submit">Leita</button>
        }
    </center>
</div>
<center>
    
    @if (ViewBag.voteSuccess != null) {
        <div class="alert alert-dismissable alert-success">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>@ViewBag.voteSuccess</strong>
        </div>
    } else if (ViewBag.votedAgain != null) {
        <div class="alert alert-dismissable alert-danger">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>@ViewBag.votedAgain</strong>
        </div>
    } else if (ViewBag.requiredLogIn != null) {
        <div class="alert alert-dismissable alert-warning">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>@ViewBag.requiredLogIn. Þú getur skráð þig inn <a href="/Account/Login">hérna</a></strong>
            
        </div>
    } 

</center>
<p>
    <a href="/Translationrequest/NewTranslationRequest" class="btn btn-info">Senda inn nýja beiðni</a>
</p>
        <table class="table table-hover table-striped table-bordered">
            <tr>
                <th>
                    Tungumál
                </th>
                <th>
                    Beiðni
                </th>
                <th>
                    Fjöldi atkvæða
                </th>
                <th></th>
                <th></th>
            </tr>

            @foreach (Textaland.Models.TranslationRequest item in ViewBag.allRequests) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item._language)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item._name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item._numUpvotes)
                    </td>
                    <td>
                        @using (Html.BeginForm("AddVote", "TranslationRequest", item, FormMethod.Post)) 
                        {
                            <center>
                                    <input type="submit" value="Like" class="btn btn-warning btn-sm" />
                            </center>
                        }
                    </td>
                    <td>
                        @if (User.Identity.IsAuthenticated) {
                            <center>
                                <a class="btn btn-warning btn-sm" href="/TranslationRequest/AnswerRequest?id=@item.Id"
                                    onclick="return confirm('Með því að svara þessari beiðni mun hún hverfa af listanum. Viltu halda áfram?')">Svara beiðni</a>
                            </center>
                        } else {
                            <center>
                                <a class="btn btn-warning btn-sm disabled" href="/TranslationRequest/AnswerRequest?id=@item.Id">Svara beiðni</a>
                            </center>
                        }
                    </td>

                </tr>

            }
        </table>

        <p>
            <a href="/Translationrequest/NewTranslationRequest" class="btn btn-info">Senda inn nýja beiðni</a>
        </p>

        
        @{
            int count = Enumerable.Count(ViewBag.countRequest);
            int numPages;

            if (count % 10 == 0) {
                numPages = count / 10;
            }
            else {
                numPages = count / 10 + 1;
            }
            int pageNumber = Convert.ToInt32(TempData["requestPageNumber"].ToString());
        }

        <ul class="pagination pagination-sm">
            @if (pageNumber != 0) { 
                <li>@Html.ActionLink("<<", "TranslationRequests", "TranslationRequest", new { num = pageNumber - 1 }, null)</li>
            }
            @for (int i = 1; i <= numPages; i++) {
                if (i - 1 == pageNumber) { 
                    <li class="active" >@Html.ActionLink(@i.ToString("#"), "TranslationRequests", "TranslationRequest", new { num = i - 1 }, null)</li>
                } else {
                    <li>@Html.ActionLink(@i.ToString("#"), "TranslationRequests", "TranslationRequest", new { num = i - 1 }, null)</li>
                }
            }
            @if (pageNumber != numPages - 1 && numPages != 0) {
                 <li>@Html.ActionLink(">>", "TranslationRequests", "TranslationRequest", new { num = pageNumber + 1 }, null)</li>
            }
        </ul>